Merge Beta Changes
* Handle precomputed recommendations

* Add Child Goals

- Added appropriate entities for child goals
- Added ChildGoalController
- Did a decent amount of cleanup, reorganizing, renaming of class goal stuff for clarity's sake, etc.
- Added tests for child goals, which involved lots of shuffling and rearranging of existing goal tests since I implemented child goals in a way that made some goal routes usable for either child or class goals

* Fix swagger folder case in git

* Fix swagger folder name to use all lowercase in git

* Deployment & Bookshelf Bug Fix

* Server now listens on all addresses (Useful for deployment)
* Fix insert bookshelf route

trigger-deploy

* Deployment URL Tweaks

* Generate Swagger UI manually from static files and generated JSON
* This allows us to rewrite URLs anyway we see fit, enabling the following:
    * bookworms.app -> rewrite URL to show swagger API docs on development and show the app when in production.
    * bookworms.app/app -> show app without index.html showing in browser URL
    * bookworms.app/api -> show swagger docs without index.html showing in browser URL
* This is helpful since subdomains require a separate process running besides ASP.NET.
    * This lets us consolidate down to one URL in a clean way.
    * Allowing us to ditch nginx and only run ASP.NET
    * Leaving the root directory free for easier user testing/discovery.

* Added classroom icons

* Added classroom icons
* Added classroom icon edit route `/homeroom/icon`

* Add `sudo` to deploy script

trigger-deploy

* Add SimilarBooks column

- Add SimilarBooks to Book schema
- Hide some stuff in test runner logs

DEPLOY FROM THIS COMMIT:  
trigger-deploy

* Add Rating & Level to BookResponsePreview

* Add classroom goals

* Added classroom goals
* Added basic route for children to log classroom goals progress
* More child-classroom goal routes to come as part of child goal routes
* Migrate script now stops on errors

* Add automatic Completed and In Progress bookshelves

- Completed, In Progress, and Classroom bookshelves are returned from the All Bookshelves endpoint in the same format as custom bookshelves (order: completed - in progress - custom - classroom)
- Removed some redundancies from related tables and cleaned up relationships
- Completed and In Progress bookshelves are now created automatically when a child is created
- Added test data for Completed and In Progress bookshelves for all test children
- Updated remaining controllers to appropriately deal with auto (and classroom) bookshelves
- Split out some repeated controller logic into helpers
- Refactored existing tests to be more flexible and also test auto bookshelves
- Added specific tests for auto bookshelves
- Split out some repeated test logic into helpers
- Added a Bookshelf abstract base class, and configured `BookwormsDbContext` to use a Table-Per-Concrete-Type approach (which means the DB schema is identical to what it was before)

* Trigger deployment off of keyphrase in commit messages

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -14,6 +14,8 @@ variables:
 # When Merge Request is opened
 
 build_job:
+    rules:
+        - if: '$CI_MERGE_REQUEST_ID'
     stage: build
     image: mcr.microsoft.com/dotnet/sdk:$DOTNET_VERSION
     script:
@@ -24,10 +26,10 @@ build_job:
             - bin/
         expire_in: 1 week
     resource_group: common
-    rules:
-        - if: '$CI_MERGE_REQUEST_ID'
 
 test_job:
+    rules:
+        - if: '$CI_MERGE_REQUEST_ID'
     stage: test
     image: mcr.microsoft.com/dotnet/sdk:$DOTNET_VERSION
     services:
@@ -54,11 +56,11 @@ test_job:
     dependencies:
         - build_job # test_job depends on artifacts produced by build_job (avoids rebuilding the project)
     resource_group: common
-    rules:
-        - if: '$CI_MERGE_REQUEST_ID'
 
 # This doesn't cause the pipeline to fail if a vulnerability is found, but vulnerabilities do get printed
 dependency_scanning:
+    rules:
+        - if: '$CI_MERGE_REQUEST_ID'
     stage: security
     image: mcr.microsoft.com/dotnet/sdk:$DOTNET_VERSION
     script:
@@ -66,16 +68,14 @@ dependency_scanning:
         - dotnet restore
         - dotnet list package --vulnerable
     resource_group: common
-    rules:
-        - if: '$CI_MERGE_REQUEST_ID'
 
 
 
-# When a merge is made into dev
+# When "trigger-deploy" is included in the commit message
 
 publish_job:
-    only:
-        - main
+    rules:
+        - if: $CI_COMMIT_MESSAGE =~ /trigger-deploy/
     stage: publish
     image: mcr.microsoft.com/dotnet/sdk:$DOTNET_VERSION
     script:
@@ -87,8 +87,8 @@ publish_job:
     resource_group: common
 
 prepare_job:
-    only:
-        - main
+    rules:
+        - if: $CI_COMMIT_MESSAGE =~ /trigger-deploy/
     stage: prepare
     image: alpine:latest
     before_script:
@@ -120,8 +120,8 @@ prepare_job:
     resource_group: common
 
 release_job:
-    only:
-        - main
+    rules:
+        - if: $CI_COMMIT_MESSAGE =~ /trigger-deploy/
     stage: release
     image: registry.gitlab.com/gitlab-org/release-cli:latest
     dependencies:
@@ -137,27 +137,43 @@ release_job:
     resource_group: common
 
 deploy_job:
-    only:
-        - main
+    rules:
+        - if: $CI_COMMIT_MESSAGE =~ /trigger-deploy/
     stage: deploy
     image: alpine:latest
     dependencies:
         - publish_job
     before_script:
-        # Install open-ssh client
-        - apk add --no-cache openssh-client
-        # Start ssh-agent
-        - eval $(ssh-agent -s)
-        # Add the private key to ssh-agent
-        - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -q -
+        - |
+          # Install open-ssh client
+          apk add --no-cache openssh-client
+          # Start ssh-agent
+          eval $(ssh-agent -s)
+          # Add the private key to ssh-agent
+          echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -q -
+          # Ensure deployment directory variable has been properly set
+          if [ -z "$DEPLOYMENT_DIR" ]; then
+            echo "ERROR: DEPLOYMENT_DIR variable is not set"
+            exit 1
+          fi
     script:
         # Replace the build artifacts in the EC2 instance, and restart the server
-        - ssh -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST 'systemctl stop bookworms.service'
-        - ssh -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST 'rm -rf $DEPLOYMENT_DIR/*'
+        - |
+          ssh -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST <<- EOF
+            sudo systemctl stop bookworms.service
+            cd \$(dirname "$DEPLOYMENT_DIR") || {
+              echo "ERROR: Failed to change to parent directory of deployment directory"
+              exit 1
+            }
+            find \$(basename "$DEPLOYMENT_DIR") -mindepth 1 -delete || {
+              echo "ERROR: Failed to clean deployment directory"
+              exit 1
+            }
+          EOF
         - scp -r -C out/* $EC2_USER@$EC2_HOST:$DEPLOYMENT_DIR
-        - ssh -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST 'systemctl start bookworms.service'
+        - ssh -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST 'sudo systemctl start bookworms.service'
     variables:
         # Don't pull the repository for this job
         GIT_STRATEGY: none
-        DEPLOYMENT_DIR: /var/www/api/
+        DEPLOYMENT_DIR: /var/www/server/
     resource_group: common
